### ISSUE TITLE
Zettelkastenタイプ実装の拡張計画

### ISSUE THREAD

**Issue by nao-amj** [nao-amj/starlight-issue-wiki#59]
# Zettelkastenタイプ実装メモ

現在、Zettelkastenタイプ（スタンダード、アトミック、階層型）の基本的な切替機能は実装されていますが、視覚的な変化が限定的であり、各モードの機能的な違いが明確ではありません。以下に将来の拡張計画をメモしておきます。

### スタンダードモード
- 基本的なWikiリンク機能のみ
- シンプルな表示スタイル

### アトミックモード
- 関連ノートの自動リンク生成
- コンセプト抽出と自動タグ付け
- 独立した小さな知識単位として視覚化
- 短く焦点を絞った内容、密接な相互リンクの推奨

### 階層型モード
- 親カテゴリと子アイテムの関係性表示
- ラベルベースの階層構造構築
- 左側のボーダーラインによる視覚的区別

## 実装ポイント

1. `src/lib/zettelkasten.ts`に追加する機能
   ```typescript
   // モード別の機能を追加
   export interface ZettelkastenConfig {
     enabled: boolean;
     autoLinkKeywords: boolean;
     highlightBidirectional: boolean;
     showBacklinks: boolean;
     keywordMinLength: number;
     visualMode: 'standard' | 'atomic' | 'hierarchical'; // モード追加
   }

   // 各モードのリンク処理を実装
   export function processContentByMode(
     content: string,
     issues: GitHubIssue[],
     currentIssueNumber: number,
     config: ZettelkastenConfig
   ): string {
     // ベース処理（全モード共通）
     let processedContent = content;
     
     switch (config.visualMode) {
       case 'atomic':
         // アトミックモード: 最小単位の知識をリンクで接続
         processedContent = processAtomicMode(processedContent, issues, currentIssueNumber);
         break;
       case 'hierarchical':
         // 階層型モード: 親子関係を構築
         processedContent = processHierarchicalMode(processedContent, issues, currentIssueNumber);
         break;
       case 'standard':
       default:
         // スタンダードモード: 基本的なリンク処理のみ
         processedContent = processStandardMode(processedContent, issues, currentIssueNumber);
         break;
     }
     
     return processedContent;
   }
   ```

2. `WikiContent.astro`の更新
   ```astro
   <div class={`wiki-content mode-${zettelkastenConfig.visualMode || 'standard'}`}>
     <MarkdownRenderer content={processedContent} />
     
     <!-- 既存のコード -->
   </div>
   ```

3. スタイルシートへの追加
   ```css
   /* モード別のベーススタイル */
   .wiki-content.mode-standard {
     /* スタンダードモードのベーススタイル */
   }
   
   .wiki-content.mode-atomic {
     padding: 0.5rem;
     border: 1px solid #eee;
     border-radius: 0.25rem;
     background-color: #fafafa;
   }
   
   .wiki-content.mode-hierarchical {
     padding-left: 1rem;
     border-left: 3px solid var(--color-primary, #4f6df5);
   }
   
   /* ダークモード対応 */
   .dark .wiki-content.mode-atomic {
     border-color: #333;
     background-color: #222;
   }
   
   .dark .wiki-content.mode-hierarchical {
     border-left-color: var(--color-primary, #4f6df5);
   }
   ```

4. `SettingsPanel.astro`の更新
   ```javascript
   // 現在のページに設定を適用
   function applySettingsToCurrentPage() {
     // 既存のコード
     
     // モード変更検知
     const previousMode = document.querySelector('.wiki-content')?.classList.contains(`mode-${config.visualMode}`) 
       ? config.visualMode 
       : null;
     
     // モード変更を反映するために、ページをリロード
     if (previousMode !== config.visualMode) {
       // モードが変更された場合は、設定を保存してからページをリロード
       localStorage.setItem('zettelkastenConfig', JSON.stringify(config));
       window.location.reload();
     }
   }
   ```

## 将来の拡張案

- **アトミックモード強化**:
  - 自然言語処理を使ったキーワード抽出
  - 自動タグ生成機能
  - 関連ノートの類似度スコアリング

- **階層型モード強化**:
  - ネストされた階層の可視化（インデントやツリービュー）
  - 親子関係の自動検出アルゴリズム
  - 階層型ナビゲーションの提供

- **グラフビジュアライゼーション**:
  - モードごとに異なる関連性表示
  - アトミックモードでは密集した関連ノードの表示
  - 階層型モードではツリー構造の可視化

- **インタラクティブ機能**:
  - ドラッグ&ドロップでのノード関係編集
  - 視覚的階層構造エディタ
  - キーワード関連性の調整

- **AIアシスト機能**:
  - 各モードに最適なコンテンツ構造提案
  - 既存コンテンツの自動構造変換
  - モード別のコンテンツ推奨

## 注意点

- 実装時にはパフォーマンスに留意する（特に大量のissueがある場合）
- 段階的に実装し、各機能のユーザビリティをテストしながら進める
- 各モードの違いを明確にするためのUIガイダンスも検討する

この計画を基にして、Zettelkastenタイプの機能を充実させていきましょう。
